### ISSUE TITLE
Generated SQL does not behave as expected

### ISSUE THREAD

**Issue by KyeTech** [TrevorPilley/MicroLite.Extensions.WebApi#50]
Hi,

I have come across a problem with the generated WHERE clauses in SQL whereby the WHERE clauses do not behave as expected given the OData filters passed through.  

If I have the filter (Formatted for readability): 
```
?$filter=Id eq 1663 and 
(
LeapYear eq true and DayOfYear gt 59 and DayOfYear eq 62 or 
LeapYear eq true and DayOfYear le 59 and DayOfYear eq 61 or 
LeapYear eq false and DayOfYear eq 61 
)
```
Given that I believe OData processes AND Before OR (See: [OData Version 3.0](http://www.odata.org/documentation/odata-version-3-0/url-conventions/), Section: 5.1.2.5. Operator Precedence), I would expect to see generated WHERE clause to look something more like:
```
WHERE Id = @p0 AND
(
	(LeapYear = @p1 AND DayOfYear > @p2 AND DayOfYear = @p3) OR
	(LeapYear = @p4 AND DayOfYear > @p5 AND DayOfYear = @p6) OR
	(LeapYear = @p7 AND DayOfYear = @p8)
)
```
Which would produce the same outcome as expected.
However the generated WHERE clause actually generates as follows:
```
WHERE 
(
	(
		(Id = @p0) AND 
		(
			(
				(
					(
						(
							(
								(
									(LeapYear = @p1) AND (DayOfYear > @p2)
								) AND (DayOfYear = @p3)
							) OR (LeapYear = @p4)
						) AND (DayOfYear <= @p5)
					) AND (DayOfYear = @p6)
				) OR (LeapYear = @p7)
			) AND (DayOfYear = @p8)
		)
	)
) 
```
This issue I believe I have with the generated WHERE clause is that it loses the grouping between the OR operators that surround the AND operators and ensure that the AND operators are run against each other prior to applying the OR operators.

Any assistance resolving this issue would be greatly appreciated.

Thanks.

**Comment by TrevorPilley** [comment]
It might just need you to specify the grouping yourself in the OData query, try this:

?$filter=Id eq 1663 and ( (LeapYear eq true and DayOfYear gt 59 and DayOfYear eq 62) or (LeapYear eq true and DayOfYear le 59 and DayOfYear eq 61) or (LeapYear eq false and DayOfYear eq 61) )
Also, you have some odd looking predicates in there - "LeapYear eq true and DayOfYear gt 59 and DayOfYear eq 62" seems weird to me, not sure why you're doing a greater than and an equals on the same property with 2 different values..

**Comment by TrevorPilley** [comment]
Formatted the example above:

```
?$filter=Id eq 1663 and 
(
(LeapYear eq true and DayOfYear gt 59 and DayOfYear eq 62) or 
(LeapYear eq true and DayOfYear le 59 and DayOfYear eq 61) or 
(LeapYear eq false and DayOfYear eq 61) 
)
```

**Comment by KyeTech** [comment]
Hi Trevor,

Thanks for the info, that does work correctly, generating appropriate SQL.
I will use the precedence grouping operators as suggested to filter these scenarios.

Many thanks.

**Comment by TrevorPilley** [comment]
No worries, glad that sorted it!

Did my comment about the `DayOfYear gt 59 and DayOfYear eq 62` make sense to you?

**Comment by KyeTech** [comment]
Yes, that sorted it thanks.

I understand why it seems a little strange and its a all to do with LeapYears and DayOfYear.
During a LeapYear the DayOfYear needs to be 1 day higher after the 59th day therefore the DayofYear would need to check for 62 rather than 61 to return the same day during a LeapYear vs a RegularYear.
Hope that makes sense to you? I am always open to suggestions on improvements.

**Comment by TrevorPilley** [comment]
I understand that part but what I wasn't sure made sense was having the `gt` and `eq` on the same property within a single predicate because if you have `(LeapYear eq true and DayOfYear gt 59 and DayOfYear eq 62)` and `DayOfYear` is not equal to `62` then it doesn't matter if it is still greater than `59`.

**Comment by KyeTech** [comment]
I see your point, it should behave the same without the `DayOfYear gt 59`, I think this was down to how we were generating the values to use but having looked at it a bit further given the information you suggest I have taken out the `DayOfYear gt 59` and adjusted the values we use accordingly.
Thanks for the suggestion, I will test the new method to ensure that it returns results in the same way.
